# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161206_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
