# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20161206_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 6, 17, 8, 29, 460000), null=True),
        ),
    ]
