# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20161206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
