# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_given',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
